# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /heka/build/ep_base/Build/lua_sandbox/ep_base/Source/lua-5_1_5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /heka/build/ep_base/Build/lua_sandbox/ep_base/Build/lua-5_1_5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Header\" \"Runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /heka/build/ep_base/Build/lua_sandbox/ep_base/Build/lua-5_1_5/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /heka/build/ep_base/Build/lua_sandbox/ep_base/Build/lua-5_1_5/CMakeFiles /heka/build/ep_base/Build/lua_sandbox/ep_base/Build/lua-5_1_5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /heka/build/ep_base/Build/lua_sandbox/ep_base/Build/lua-5_1_5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named liblua

# Build rule for target.
liblua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 liblua
.PHONY : liblua

# fast build rule for target.
liblua/fast:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/build
.PHONY : liblua/fast

src/lapi.o: src/lapi.c.o
.PHONY : src/lapi.o

# target to build an object file
src/lapi.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lapi.c.o
.PHONY : src/lapi.c.o

src/lapi.i: src/lapi.c.i
.PHONY : src/lapi.i

# target to preprocess a source file
src/lapi.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lapi.c.i
.PHONY : src/lapi.c.i

src/lapi.s: src/lapi.c.s
.PHONY : src/lapi.s

# target to generate assembly for a file
src/lapi.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lapi.c.s
.PHONY : src/lapi.c.s

src/lauxlib.o: src/lauxlib.c.o
.PHONY : src/lauxlib.o

# target to build an object file
src/lauxlib.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lauxlib.c.o
.PHONY : src/lauxlib.c.o

src/lauxlib.i: src/lauxlib.c.i
.PHONY : src/lauxlib.i

# target to preprocess a source file
src/lauxlib.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lauxlib.c.i
.PHONY : src/lauxlib.c.i

src/lauxlib.s: src/lauxlib.c.s
.PHONY : src/lauxlib.s

# target to generate assembly for a file
src/lauxlib.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lauxlib.c.s
.PHONY : src/lauxlib.c.s

src/lbaselib.o: src/lbaselib.c.o
.PHONY : src/lbaselib.o

# target to build an object file
src/lbaselib.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lbaselib.c.o
.PHONY : src/lbaselib.c.o

src/lbaselib.i: src/lbaselib.c.i
.PHONY : src/lbaselib.i

# target to preprocess a source file
src/lbaselib.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lbaselib.c.i
.PHONY : src/lbaselib.c.i

src/lbaselib.s: src/lbaselib.c.s
.PHONY : src/lbaselib.s

# target to generate assembly for a file
src/lbaselib.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lbaselib.c.s
.PHONY : src/lbaselib.c.s

src/lcode.o: src/lcode.c.o
.PHONY : src/lcode.o

# target to build an object file
src/lcode.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lcode.c.o
.PHONY : src/lcode.c.o

src/lcode.i: src/lcode.c.i
.PHONY : src/lcode.i

# target to preprocess a source file
src/lcode.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lcode.c.i
.PHONY : src/lcode.c.i

src/lcode.s: src/lcode.c.s
.PHONY : src/lcode.s

# target to generate assembly for a file
src/lcode.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lcode.c.s
.PHONY : src/lcode.c.s

src/ldblib.o: src/ldblib.c.o
.PHONY : src/ldblib.o

# target to build an object file
src/ldblib.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldblib.c.o
.PHONY : src/ldblib.c.o

src/ldblib.i: src/ldblib.c.i
.PHONY : src/ldblib.i

# target to preprocess a source file
src/ldblib.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldblib.c.i
.PHONY : src/ldblib.c.i

src/ldblib.s: src/ldblib.c.s
.PHONY : src/ldblib.s

# target to generate assembly for a file
src/ldblib.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldblib.c.s
.PHONY : src/ldblib.c.s

src/ldebug.o: src/ldebug.c.o
.PHONY : src/ldebug.o

# target to build an object file
src/ldebug.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldebug.c.o
.PHONY : src/ldebug.c.o

src/ldebug.i: src/ldebug.c.i
.PHONY : src/ldebug.i

# target to preprocess a source file
src/ldebug.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldebug.c.i
.PHONY : src/ldebug.c.i

src/ldebug.s: src/ldebug.c.s
.PHONY : src/ldebug.s

# target to generate assembly for a file
src/ldebug.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldebug.c.s
.PHONY : src/ldebug.c.s

src/ldo.o: src/ldo.c.o
.PHONY : src/ldo.o

# target to build an object file
src/ldo.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldo.c.o
.PHONY : src/ldo.c.o

src/ldo.i: src/ldo.c.i
.PHONY : src/ldo.i

# target to preprocess a source file
src/ldo.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldo.c.i
.PHONY : src/ldo.c.i

src/ldo.s: src/ldo.c.s
.PHONY : src/ldo.s

# target to generate assembly for a file
src/ldo.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldo.c.s
.PHONY : src/ldo.c.s

src/ldump.o: src/ldump.c.o
.PHONY : src/ldump.o

# target to build an object file
src/ldump.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldump.c.o
.PHONY : src/ldump.c.o

src/ldump.i: src/ldump.c.i
.PHONY : src/ldump.i

# target to preprocess a source file
src/ldump.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldump.c.i
.PHONY : src/ldump.c.i

src/ldump.s: src/ldump.c.s
.PHONY : src/ldump.s

# target to generate assembly for a file
src/ldump.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ldump.c.s
.PHONY : src/ldump.c.s

src/lfunc.o: src/lfunc.c.o
.PHONY : src/lfunc.o

# target to build an object file
src/lfunc.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lfunc.c.o
.PHONY : src/lfunc.c.o

src/lfunc.i: src/lfunc.c.i
.PHONY : src/lfunc.i

# target to preprocess a source file
src/lfunc.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lfunc.c.i
.PHONY : src/lfunc.c.i

src/lfunc.s: src/lfunc.c.s
.PHONY : src/lfunc.s

# target to generate assembly for a file
src/lfunc.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lfunc.c.s
.PHONY : src/lfunc.c.s

src/lgc.o: src/lgc.c.o
.PHONY : src/lgc.o

# target to build an object file
src/lgc.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lgc.c.o
.PHONY : src/lgc.c.o

src/lgc.i: src/lgc.c.i
.PHONY : src/lgc.i

# target to preprocess a source file
src/lgc.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lgc.c.i
.PHONY : src/lgc.c.i

src/lgc.s: src/lgc.c.s
.PHONY : src/lgc.s

# target to generate assembly for a file
src/lgc.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lgc.c.s
.PHONY : src/lgc.c.s

src/linit.o: src/linit.c.o
.PHONY : src/linit.o

# target to build an object file
src/linit.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/linit.c.o
.PHONY : src/linit.c.o

src/linit.i: src/linit.c.i
.PHONY : src/linit.i

# target to preprocess a source file
src/linit.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/linit.c.i
.PHONY : src/linit.c.i

src/linit.s: src/linit.c.s
.PHONY : src/linit.s

# target to generate assembly for a file
src/linit.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/linit.c.s
.PHONY : src/linit.c.s

src/liolib.o: src/liolib.c.o
.PHONY : src/liolib.o

# target to build an object file
src/liolib.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/liolib.c.o
.PHONY : src/liolib.c.o

src/liolib.i: src/liolib.c.i
.PHONY : src/liolib.i

# target to preprocess a source file
src/liolib.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/liolib.c.i
.PHONY : src/liolib.c.i

src/liolib.s: src/liolib.c.s
.PHONY : src/liolib.s

# target to generate assembly for a file
src/liolib.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/liolib.c.s
.PHONY : src/liolib.c.s

src/llex.o: src/llex.c.o
.PHONY : src/llex.o

# target to build an object file
src/llex.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/llex.c.o
.PHONY : src/llex.c.o

src/llex.i: src/llex.c.i
.PHONY : src/llex.i

# target to preprocess a source file
src/llex.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/llex.c.i
.PHONY : src/llex.c.i

src/llex.s: src/llex.c.s
.PHONY : src/llex.s

# target to generate assembly for a file
src/llex.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/llex.c.s
.PHONY : src/llex.c.s

src/lmathlib.o: src/lmathlib.c.o
.PHONY : src/lmathlib.o

# target to build an object file
src/lmathlib.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lmathlib.c.o
.PHONY : src/lmathlib.c.o

src/lmathlib.i: src/lmathlib.c.i
.PHONY : src/lmathlib.i

# target to preprocess a source file
src/lmathlib.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lmathlib.c.i
.PHONY : src/lmathlib.c.i

src/lmathlib.s: src/lmathlib.c.s
.PHONY : src/lmathlib.s

# target to generate assembly for a file
src/lmathlib.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lmathlib.c.s
.PHONY : src/lmathlib.c.s

src/lmem.o: src/lmem.c.o
.PHONY : src/lmem.o

# target to build an object file
src/lmem.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lmem.c.o
.PHONY : src/lmem.c.o

src/lmem.i: src/lmem.c.i
.PHONY : src/lmem.i

# target to preprocess a source file
src/lmem.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lmem.c.i
.PHONY : src/lmem.c.i

src/lmem.s: src/lmem.c.s
.PHONY : src/lmem.s

# target to generate assembly for a file
src/lmem.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lmem.c.s
.PHONY : src/lmem.c.s

src/loadlib.o: src/loadlib.c.o
.PHONY : src/loadlib.o

# target to build an object file
src/loadlib.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/loadlib.c.o
.PHONY : src/loadlib.c.o

src/loadlib.i: src/loadlib.c.i
.PHONY : src/loadlib.i

# target to preprocess a source file
src/loadlib.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/loadlib.c.i
.PHONY : src/loadlib.c.i

src/loadlib.s: src/loadlib.c.s
.PHONY : src/loadlib.s

# target to generate assembly for a file
src/loadlib.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/loadlib.c.s
.PHONY : src/loadlib.c.s

src/lobject.o: src/lobject.c.o
.PHONY : src/lobject.o

# target to build an object file
src/lobject.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lobject.c.o
.PHONY : src/lobject.c.o

src/lobject.i: src/lobject.c.i
.PHONY : src/lobject.i

# target to preprocess a source file
src/lobject.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lobject.c.i
.PHONY : src/lobject.c.i

src/lobject.s: src/lobject.c.s
.PHONY : src/lobject.s

# target to generate assembly for a file
src/lobject.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lobject.c.s
.PHONY : src/lobject.c.s

src/lopcodes.o: src/lopcodes.c.o
.PHONY : src/lopcodes.o

# target to build an object file
src/lopcodes.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lopcodes.c.o
.PHONY : src/lopcodes.c.o

src/lopcodes.i: src/lopcodes.c.i
.PHONY : src/lopcodes.i

# target to preprocess a source file
src/lopcodes.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lopcodes.c.i
.PHONY : src/lopcodes.c.i

src/lopcodes.s: src/lopcodes.c.s
.PHONY : src/lopcodes.s

# target to generate assembly for a file
src/lopcodes.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lopcodes.c.s
.PHONY : src/lopcodes.c.s

src/loslib.o: src/loslib.c.o
.PHONY : src/loslib.o

# target to build an object file
src/loslib.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/loslib.c.o
.PHONY : src/loslib.c.o

src/loslib.i: src/loslib.c.i
.PHONY : src/loslib.i

# target to preprocess a source file
src/loslib.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/loslib.c.i
.PHONY : src/loslib.c.i

src/loslib.s: src/loslib.c.s
.PHONY : src/loslib.s

# target to generate assembly for a file
src/loslib.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/loslib.c.s
.PHONY : src/loslib.c.s

src/lparser.o: src/lparser.c.o
.PHONY : src/lparser.o

# target to build an object file
src/lparser.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lparser.c.o
.PHONY : src/lparser.c.o

src/lparser.i: src/lparser.c.i
.PHONY : src/lparser.i

# target to preprocess a source file
src/lparser.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lparser.c.i
.PHONY : src/lparser.c.i

src/lparser.s: src/lparser.c.s
.PHONY : src/lparser.s

# target to generate assembly for a file
src/lparser.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lparser.c.s
.PHONY : src/lparser.c.s

src/lstate.o: src/lstate.c.o
.PHONY : src/lstate.o

# target to build an object file
src/lstate.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lstate.c.o
.PHONY : src/lstate.c.o

src/lstate.i: src/lstate.c.i
.PHONY : src/lstate.i

# target to preprocess a source file
src/lstate.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lstate.c.i
.PHONY : src/lstate.c.i

src/lstate.s: src/lstate.c.s
.PHONY : src/lstate.s

# target to generate assembly for a file
src/lstate.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lstate.c.s
.PHONY : src/lstate.c.s

src/lstring.o: src/lstring.c.o
.PHONY : src/lstring.o

# target to build an object file
src/lstring.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lstring.c.o
.PHONY : src/lstring.c.o

src/lstring.i: src/lstring.c.i
.PHONY : src/lstring.i

# target to preprocess a source file
src/lstring.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lstring.c.i
.PHONY : src/lstring.c.i

src/lstring.s: src/lstring.c.s
.PHONY : src/lstring.s

# target to generate assembly for a file
src/lstring.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lstring.c.s
.PHONY : src/lstring.c.s

src/lstrlib.o: src/lstrlib.c.o
.PHONY : src/lstrlib.o

# target to build an object file
src/lstrlib.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lstrlib.c.o
.PHONY : src/lstrlib.c.o

src/lstrlib.i: src/lstrlib.c.i
.PHONY : src/lstrlib.i

# target to preprocess a source file
src/lstrlib.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lstrlib.c.i
.PHONY : src/lstrlib.c.i

src/lstrlib.s: src/lstrlib.c.s
.PHONY : src/lstrlib.s

# target to generate assembly for a file
src/lstrlib.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lstrlib.c.s
.PHONY : src/lstrlib.c.s

src/ltable.o: src/ltable.c.o
.PHONY : src/ltable.o

# target to build an object file
src/ltable.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ltable.c.o
.PHONY : src/ltable.c.o

src/ltable.i: src/ltable.c.i
.PHONY : src/ltable.i

# target to preprocess a source file
src/ltable.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ltable.c.i
.PHONY : src/ltable.c.i

src/ltable.s: src/ltable.c.s
.PHONY : src/ltable.s

# target to generate assembly for a file
src/ltable.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ltable.c.s
.PHONY : src/ltable.c.s

src/ltablib.o: src/ltablib.c.o
.PHONY : src/ltablib.o

# target to build an object file
src/ltablib.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ltablib.c.o
.PHONY : src/ltablib.c.o

src/ltablib.i: src/ltablib.c.i
.PHONY : src/ltablib.i

# target to preprocess a source file
src/ltablib.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ltablib.c.i
.PHONY : src/ltablib.c.i

src/ltablib.s: src/ltablib.c.s
.PHONY : src/ltablib.s

# target to generate assembly for a file
src/ltablib.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ltablib.c.s
.PHONY : src/ltablib.c.s

src/ltm.o: src/ltm.c.o
.PHONY : src/ltm.o

# target to build an object file
src/ltm.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ltm.c.o
.PHONY : src/ltm.c.o

src/ltm.i: src/ltm.c.i
.PHONY : src/ltm.i

# target to preprocess a source file
src/ltm.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ltm.c.i
.PHONY : src/ltm.c.i

src/ltm.s: src/ltm.c.s
.PHONY : src/ltm.s

# target to generate assembly for a file
src/ltm.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/ltm.c.s
.PHONY : src/ltm.c.s

src/lundump.o: src/lundump.c.o
.PHONY : src/lundump.o

# target to build an object file
src/lundump.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lundump.c.o
.PHONY : src/lundump.c.o

src/lundump.i: src/lundump.c.i
.PHONY : src/lundump.i

# target to preprocess a source file
src/lundump.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lundump.c.i
.PHONY : src/lundump.c.i

src/lundump.s: src/lundump.c.s
.PHONY : src/lundump.s

# target to generate assembly for a file
src/lundump.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lundump.c.s
.PHONY : src/lundump.c.s

src/lvm.o: src/lvm.c.o
.PHONY : src/lvm.o

# target to build an object file
src/lvm.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lvm.c.o
.PHONY : src/lvm.c.o

src/lvm.i: src/lvm.c.i
.PHONY : src/lvm.i

# target to preprocess a source file
src/lvm.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lvm.c.i
.PHONY : src/lvm.c.i

src/lvm.s: src/lvm.c.s
.PHONY : src/lvm.s

# target to generate assembly for a file
src/lvm.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lvm.c.s
.PHONY : src/lvm.c.s

src/lzio.o: src/lzio.c.o
.PHONY : src/lzio.o

# target to build an object file
src/lzio.c.o:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lzio.c.o
.PHONY : src/lzio.c.o

src/lzio.i: src/lzio.c.i
.PHONY : src/lzio.i

# target to preprocess a source file
src/lzio.c.i:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lzio.c.i
.PHONY : src/lzio.c.i

src/lzio.s: src/lzio.c.s
.PHONY : src/lzio.s

# target to generate assembly for a file
src/lzio.c.s:
	$(MAKE) -f CMakeFiles/liblua.dir/build.make CMakeFiles/liblua.dir/src/lzio.c.s
.PHONY : src/lzio.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... liblua"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... src/lapi.o"
	@echo "... src/lapi.i"
	@echo "... src/lapi.s"
	@echo "... src/lauxlib.o"
	@echo "... src/lauxlib.i"
	@echo "... src/lauxlib.s"
	@echo "... src/lbaselib.o"
	@echo "... src/lbaselib.i"
	@echo "... src/lbaselib.s"
	@echo "... src/lcode.o"
	@echo "... src/lcode.i"
	@echo "... src/lcode.s"
	@echo "... src/ldblib.o"
	@echo "... src/ldblib.i"
	@echo "... src/ldblib.s"
	@echo "... src/ldebug.o"
	@echo "... src/ldebug.i"
	@echo "... src/ldebug.s"
	@echo "... src/ldo.o"
	@echo "... src/ldo.i"
	@echo "... src/ldo.s"
	@echo "... src/ldump.o"
	@echo "... src/ldump.i"
	@echo "... src/ldump.s"
	@echo "... src/lfunc.o"
	@echo "... src/lfunc.i"
	@echo "... src/lfunc.s"
	@echo "... src/lgc.o"
	@echo "... src/lgc.i"
	@echo "... src/lgc.s"
	@echo "... src/linit.o"
	@echo "... src/linit.i"
	@echo "... src/linit.s"
	@echo "... src/liolib.o"
	@echo "... src/liolib.i"
	@echo "... src/liolib.s"
	@echo "... src/llex.o"
	@echo "... src/llex.i"
	@echo "... src/llex.s"
	@echo "... src/lmathlib.o"
	@echo "... src/lmathlib.i"
	@echo "... src/lmathlib.s"
	@echo "... src/lmem.o"
	@echo "... src/lmem.i"
	@echo "... src/lmem.s"
	@echo "... src/loadlib.o"
	@echo "... src/loadlib.i"
	@echo "... src/loadlib.s"
	@echo "... src/lobject.o"
	@echo "... src/lobject.i"
	@echo "... src/lobject.s"
	@echo "... src/lopcodes.o"
	@echo "... src/lopcodes.i"
	@echo "... src/lopcodes.s"
	@echo "... src/loslib.o"
	@echo "... src/loslib.i"
	@echo "... src/loslib.s"
	@echo "... src/lparser.o"
	@echo "... src/lparser.i"
	@echo "... src/lparser.s"
	@echo "... src/lstate.o"
	@echo "... src/lstate.i"
	@echo "... src/lstate.s"
	@echo "... src/lstring.o"
	@echo "... src/lstring.i"
	@echo "... src/lstring.s"
	@echo "... src/lstrlib.o"
	@echo "... src/lstrlib.i"
	@echo "... src/lstrlib.s"
	@echo "... src/ltable.o"
	@echo "... src/ltable.i"
	@echo "... src/ltable.s"
	@echo "... src/ltablib.o"
	@echo "... src/ltablib.i"
	@echo "... src/ltablib.s"
	@echo "... src/ltm.o"
	@echo "... src/ltm.i"
	@echo "... src/ltm.s"
	@echo "... src/lundump.o"
	@echo "... src/lundump.i"
	@echo "... src/lundump.s"
	@echo "... src/lvm.o"
	@echo "... src/lvm.i"
	@echo "... src/lvm.s"
	@echo "... src/lzio.o"
	@echo "... src/lzio.i"
	@echo "... src/lzio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

